services:
  - type: web
    name: folio-proxy
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PIXELDRAIN_KEY
        value: 11e5a07e-366f-44aa-a207-1ab3cf7241ed
