services:
  - type: web
    name: folio-proxy
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PIXELDRAIN_KEY
        sync: false
      - key: PUBLIC_BASE_URL
        value: https://renderproxy-9q2i.onrender.com
