services:
  - type: web
    name: folio-proxy
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PIXELDRAIN_KEY
        value: f6d13e61-9fb2-4a55-818e-57346d848afa
